// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.hantsylabs.example.spring.conference.model;

import com.hantsylabs.example.spring.conference.model.Conference;
import com.hantsylabs.example.spring.conference.model.ConferenceDataOnDemand;
import com.hantsylabs.example.spring.conference.repository.ConferenceRepository;
import com.hantsylabs.example.spring.conference.service.ConferenceService;
import java.security.SecureRandom;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.Date;
import java.util.GregorianCalendar;
import java.util.Iterator;
import java.util.List;
import java.util.Random;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Component;

privileged aspect ConferenceDataOnDemand_Roo_DataOnDemand {
    
    declare @type: ConferenceDataOnDemand: @Component;
    
    private Random ConferenceDataOnDemand.rnd = new SecureRandom();
    
    private List<Conference> ConferenceDataOnDemand.data;
    
    @Autowired
    ConferenceService ConferenceDataOnDemand.conferenceService;
    
    @Autowired
    ConferenceRepository ConferenceDataOnDemand.conferenceRepository;
    
    public Conference ConferenceDataOnDemand.getNewTransientConference(int index) {
        Conference obj = new Conference();
        setDescription(obj, index);
        setEndedDate(obj, index);
        setName(obj, index);
        setSlug(obj, index);
        return obj;
    }
    
    public void ConferenceDataOnDemand.setDescription(Conference obj, int index) {
        String description = "description_" + index;
        obj.setDescription(description);
    }
    
    public void ConferenceDataOnDemand.setEndedDate(Conference obj, int index) {
        Date endedDate = new GregorianCalendar(Calendar.getInstance().get(Calendar.YEAR), Calendar.getInstance().get(Calendar.MONTH), Calendar.getInstance().get(Calendar.DAY_OF_MONTH), Calendar.getInstance().get(Calendar.HOUR_OF_DAY), Calendar.getInstance().get(Calendar.MINUTE), Calendar.getInstance().get(Calendar.SECOND) + new Double(Math.random() * 1000).intValue()).getTime();
        obj.setEndedDate(endedDate);
    }
    
    public void ConferenceDataOnDemand.setName(Conference obj, int index) {
        String name = "name_" + index;
        obj.setName(name);
    }
    
    public void ConferenceDataOnDemand.setSlug(Conference obj, int index) {
        String slug = "slug_" + index;
        obj.setSlug(slug);
    }
    
    public Conference ConferenceDataOnDemand.getSpecificConference(int index) {
        init();
        if (index < 0) {
            index = 0;
        }
        if (index > (data.size() - 1)) {
            index = data.size() - 1;
        }
        Conference obj = data.get(index);
        Long id = obj.getId();
        return conferenceService.findConference(id);
    }
    
    public Conference ConferenceDataOnDemand.getRandomConference() {
        init();
        Conference obj = data.get(rnd.nextInt(data.size()));
        Long id = obj.getId();
        return conferenceService.findConference(id);
    }
    
    public boolean ConferenceDataOnDemand.modifyConference(Conference obj) {
        return false;
    }
    
    public void ConferenceDataOnDemand.init() {
        int from = 0;
        int to = 10;
        data = conferenceService.findConferenceEntries(from, to);
        if (data == null) {
            throw new IllegalStateException("Find entries implementation for 'Conference' illegally returned null");
        }
        if (!data.isEmpty()) {
            return;
        }
        
        data = new ArrayList<Conference>();
        for (int i = 0; i < 10; i++) {
            Conference obj = getNewTransientConference(i);
            try {
                conferenceService.saveConference(obj);
            } catch (ConstraintViolationException e) {
                StringBuilder msg = new StringBuilder();
                for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                    ConstraintViolation<?> cv = iter.next();
                    msg.append("[").append(cv.getConstraintDescriptor()).append(":").append(cv.getMessage()).append("=").append(cv.getInvalidValue()).append("]");
                }
                throw new RuntimeException(msg.toString(), e);
            }
            conferenceRepository.flush();
            data.add(obj);
        }
    }
    
}
