// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.hantsylabs.example.spring.conference.model;

import com.hantsylabs.example.spring.conference.model.ConferenceDataOnDemand;
import com.hantsylabs.example.spring.conference.model.ConferenceIntegrationTest;
import com.hantsylabs.example.spring.conference.repository.ConferenceRepository;
import com.hantsylabs.example.spring.conference.service.ConferenceService;
import java.util.List;
import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect ConferenceIntegrationTest_Roo_IntegrationTest {
    
    declare @type: ConferenceIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: ConferenceIntegrationTest: @ContextConfiguration(locations = "classpath:/META-INF/spring/applicationContext*.xml");
    
    declare @type: ConferenceIntegrationTest: @Transactional;
    
    @Autowired
    ConferenceDataOnDemand ConferenceIntegrationTest.dod;
    
    @Autowired
    ConferenceService ConferenceIntegrationTest.conferenceService;
    
    @Autowired
    ConferenceRepository ConferenceIntegrationTest.conferenceRepository;
    
    @Test
    public void ConferenceIntegrationTest.testCountAllConferences() {
        Assert.assertNotNull("Data on demand for 'Conference' failed to initialize correctly", dod.getRandomConference());
        long count = conferenceService.countAllConferences();
        Assert.assertTrue("Counter for 'Conference' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void ConferenceIntegrationTest.testFindConference() {
        Conference obj = dod.getRandomConference();
        Assert.assertNotNull("Data on demand for 'Conference' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Conference' failed to provide an identifier", id);
        obj = conferenceService.findConference(id);
        Assert.assertNotNull("Find method for 'Conference' illegally returned null for id '" + id + "'", obj);
        Assert.assertEquals("Find method for 'Conference' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void ConferenceIntegrationTest.testFindAllConferences() {
        Assert.assertNotNull("Data on demand for 'Conference' failed to initialize correctly", dod.getRandomConference());
        long count = conferenceService.countAllConferences();
        Assert.assertTrue("Too expensive to perform a find all test for 'Conference', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        List<Conference> result = conferenceService.findAllConferences();
        Assert.assertNotNull("Find all method for 'Conference' illegally returned null", result);
        Assert.assertTrue("Find all method for 'Conference' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void ConferenceIntegrationTest.testFindConferenceEntries() {
        Assert.assertNotNull("Data on demand for 'Conference' failed to initialize correctly", dod.getRandomConference());
        long count = conferenceService.countAllConferences();
        if (count > 20) count = 20;
        int firstResult = 0;
        int maxResults = (int) count;
        List<Conference> result = conferenceService.findConferenceEntries(firstResult, maxResults);
        Assert.assertNotNull("Find entries method for 'Conference' illegally returned null", result);
        Assert.assertEquals("Find entries method for 'Conference' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void ConferenceIntegrationTest.testFlush() {
        Conference obj = dod.getRandomConference();
        Assert.assertNotNull("Data on demand for 'Conference' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Conference' failed to provide an identifier", id);
        obj = conferenceService.findConference(id);
        Assert.assertNotNull("Find method for 'Conference' illegally returned null for id '" + id + "'", obj);
        boolean modified =  dod.modifyConference(obj);
        Integer currentVersion = obj.getVersion();
        conferenceRepository.flush();
        Assert.assertTrue("Version for 'Conference' failed to increment on flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void ConferenceIntegrationTest.testUpdateConferenceUpdate() {
        Conference obj = dod.getRandomConference();
        Assert.assertNotNull("Data on demand for 'Conference' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Conference' failed to provide an identifier", id);
        obj = conferenceService.findConference(id);
        boolean modified =  dod.modifyConference(obj);
        Integer currentVersion = obj.getVersion();
        Conference merged = conferenceService.updateConference(obj);
        conferenceRepository.flush();
        Assert.assertEquals("Identifier of merged object not the same as identifier of original object", merged.getId(), id);
        Assert.assertTrue("Version for 'Conference' failed to increment on merge and flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void ConferenceIntegrationTest.testSaveConference() {
        Assert.assertNotNull("Data on demand for 'Conference' failed to initialize correctly", dod.getRandomConference());
        Conference obj = dod.getNewTransientConference(Integer.MAX_VALUE);
        Assert.assertNotNull("Data on demand for 'Conference' failed to provide a new transient entity", obj);
        Assert.assertNull("Expected 'Conference' identifier to be null", obj.getId());
        conferenceService.saveConference(obj);
        conferenceRepository.flush();
        Assert.assertNotNull("Expected 'Conference' identifier to no longer be null", obj.getId());
    }
    
    @Test
    public void ConferenceIntegrationTest.testDeleteConference() {
        Conference obj = dod.getRandomConference();
        Assert.assertNotNull("Data on demand for 'Conference' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Conference' failed to provide an identifier", id);
        obj = conferenceService.findConference(id);
        conferenceService.deleteConference(obj);
        conferenceRepository.flush();
        Assert.assertNull("Failed to remove 'Conference' with identifier '" + id + "'", conferenceService.findConference(id));
    }
    
}
