// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.hantsylabs.example.spring.conference.model;

import com.hantsylabs.example.spring.conference.model.SignupDataOnDemand;
import org.springframework.beans.factory.annotation.Configurable;

privileged aspect SignupDataOnDemand_Roo_Configurable {
    
    declare @type: SignupDataOnDemand: @Configurable;
    
}
