// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.hantsylabs.example.spring.conference.model;

import com.hantsylabs.example.spring.conference.model.Signup;
import com.hantsylabs.example.spring.conference.model.SignupDataOnDemand;
import com.hantsylabs.example.spring.conference.model.SignupIntegrationTest;
import java.util.List;
import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect SignupIntegrationTest_Roo_IntegrationTest {
    
    declare @type: SignupIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: SignupIntegrationTest: @ContextConfiguration(locations = "classpath:/META-INF/spring/applicationContext*.xml");
    
    declare @type: SignupIntegrationTest: @Transactional;
    
    @Autowired
    SignupDataOnDemand SignupIntegrationTest.dod;
    
    @Test
    public void SignupIntegrationTest.testCountSignups() {
        Assert.assertNotNull("Data on demand for 'Signup' failed to initialize correctly", dod.getRandomSignup());
        long count = Signup.countSignups();
        Assert.assertTrue("Counter for 'Signup' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void SignupIntegrationTest.testFindSignup() {
        Signup obj = dod.getRandomSignup();
        Assert.assertNotNull("Data on demand for 'Signup' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Signup' failed to provide an identifier", id);
        obj = Signup.findSignup(id);
        Assert.assertNotNull("Find method for 'Signup' illegally returned null for id '" + id + "'", obj);
        Assert.assertEquals("Find method for 'Signup' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void SignupIntegrationTest.testFindAllSignups() {
        Assert.assertNotNull("Data on demand for 'Signup' failed to initialize correctly", dod.getRandomSignup());
        long count = Signup.countSignups();
        Assert.assertTrue("Too expensive to perform a find all test for 'Signup', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        List<Signup> result = Signup.findAllSignups();
        Assert.assertNotNull("Find all method for 'Signup' illegally returned null", result);
        Assert.assertTrue("Find all method for 'Signup' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void SignupIntegrationTest.testFindSignupEntries() {
        Assert.assertNotNull("Data on demand for 'Signup' failed to initialize correctly", dod.getRandomSignup());
        long count = Signup.countSignups();
        if (count > 20) count = 20;
        int firstResult = 0;
        int maxResults = (int) count;
        List<Signup> result = Signup.findSignupEntries(firstResult, maxResults);
        Assert.assertNotNull("Find entries method for 'Signup' illegally returned null", result);
        Assert.assertEquals("Find entries method for 'Signup' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void SignupIntegrationTest.testFlush() {
        Signup obj = dod.getRandomSignup();
        Assert.assertNotNull("Data on demand for 'Signup' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Signup' failed to provide an identifier", id);
        obj = Signup.findSignup(id);
        Assert.assertNotNull("Find method for 'Signup' illegally returned null for id '" + id + "'", obj);
        boolean modified =  dod.modifySignup(obj);
        Integer currentVersion = obj.getVersion();
        obj.flush();
        Assert.assertTrue("Version for 'Signup' failed to increment on flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void SignupIntegrationTest.testMergeUpdate() {
        Signup obj = dod.getRandomSignup();
        Assert.assertNotNull("Data on demand for 'Signup' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Signup' failed to provide an identifier", id);
        obj = Signup.findSignup(id);
        boolean modified =  dod.modifySignup(obj);
        Integer currentVersion = obj.getVersion();
        Signup merged = obj.merge();
        obj.flush();
        Assert.assertEquals("Identifier of merged object not the same as identifier of original object", merged.getId(), id);
        Assert.assertTrue("Version for 'Signup' failed to increment on merge and flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void SignupIntegrationTest.testPersist() {
        Assert.assertNotNull("Data on demand for 'Signup' failed to initialize correctly", dod.getRandomSignup());
        Signup obj = dod.getNewTransientSignup(Integer.MAX_VALUE);
        Assert.assertNotNull("Data on demand for 'Signup' failed to provide a new transient entity", obj);
        Assert.assertNull("Expected 'Signup' identifier to be null", obj.getId());
        obj.persist();
        obj.flush();
        Assert.assertNotNull("Expected 'Signup' identifier to no longer be null", obj.getId());
    }
    
    @Test
    public void SignupIntegrationTest.testRemove() {
        Signup obj = dod.getRandomSignup();
        Assert.assertNotNull("Data on demand for 'Signup' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Signup' failed to provide an identifier", id);
        obj = Signup.findSignup(id);
        obj.remove();
        obj.flush();
        Assert.assertNull("Failed to remove 'Signup' with identifier '" + id + "'", Signup.findSignup(id));
    }
    
}
